name: delight-app
services:
  app:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.40
    expose:
      - "3306"
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: delightdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  mailhog:
    image: mailhog/mailhog:v1.0.1
    expose:
      - "1025"
    ports:
      - "8025:8025"
